### ISSUE TITLE
Check if username is already taken without being admin with getUser('')

### ISSUE THREAD

**Issue by matikbird** [pouchdb-community/pouchdb-authentication#136]
I would like to know how can I do this without using Nano, just plain Pouch/Couch

Thanks in advance! Any ideas are appreciate!

**Comment by matikbird** [comment]
```
db.getUser('aquaman', function (err, response) {
  if (err) {
    if (err.name === 'not_found') {
  // user unavaible, proceed signUp()
    } else {
 // errir
    }
  } else {
   //user avaible! proceed with another function login()
  }
});
```

@nolanlawson this works as long as I am logged in Futon as Admin.
But, if I'm not logged as admin, this shows up:

> "Only admins can access _all_docs of system databases."

And I can't move on. Don't know how to proceed.
Please, help.

**Comment by dweremeichik** [comment]
@matikbird This is a limitation of CouchDB. It would be dangerous for the database to expose every possible user to the public; which is why:

1. Only admins can view all user data.
1. Users can only view their own data.

Per the documentation (see the note line at the bottom of this section): https://github.com/nolanlawson/pouchdb-authentication#dbgetuserusername--opts-callback

For what it is worth, you don't have to use nano, you can use pouchdb; but to get what you want you will still have to run something on a server.

**Comment by skiqh** [comment]
You can expose one or more fields of a user's document (see [public_fields](http://docs.couchdb.org/en/latest/config/auth.html?highlight=public_fields#couch_httpd_auth/public_fields)), which makes unauthorized queries to that document to succeed, showing only those exposed fields.

**Comment by ptitjes** [comment]
@matikbird I believe @skiqh's answer gave you an acceptable solution to your problem.
Can we close this issue ?

**Comment by ptitjes** [comment]
As @skiqh's solution is reasonable, let me close this issue.

**Comment by mqtik** [comment]
3 years later:
Thanks.

It's funny, because now I'm experiencing the same problem, with public_fields activated. 🤦
