### ISSUE TITLE
Ask - Can auto logout user after idle for N minutes?

### ISSUE THREAD

**Issue by dodomui** [pouchdb-community/pouchdb-authentication#161]
Building web backend with AngularJS + Cloudant pouchDB + pouchdb-authentication.

Need auto logout while user idle for N minutes.

Any possible?

**Comment by dodomui** [comment]
Appreciate if anyone could help.

**Comment by ptitjes** [comment]
@dodomui Can't you implement that at your application level? You just have to put a timer, refresh the timer when your user do stuff and call our logout method when the timer triggers. If you need more help, you will find more people able to give you hints on StackOverflow because it is unrelated to pouchdb-authentication.

I think it is out of the scope of this library. I will close this issue.
