### ISSUE TITLE
Pouchdb authentication not working

### ISSUE THREAD

**Issue by mehrajpasha** [pouchdb-community/pouchdb-authentication#206]
I'm using couchdb with ember. After logging into db, when I come into my application and try to login, It's asking for authentication again. The expected behaviour of my application should be when I login through my application, the db should automatically login. Please help ?

**Comment by ptitjes** [comment]
@mehrajpasha In its current form, your issue is not detailed enough for anybody to be able to help you. So I will close it so that you can open a new one. **There is an issue template.** Rather than deleting its content, you should follow the template and answer the requested questions. Please help us help you...
