### ISSUE TITLE
Couchdb cookie doesn't show up in DevTools

### ISSUE THREAD

**Issue by uyouthe** [pouchdb-community/pouchdb-authentication#224]
Hello!

It seems like I can successfully log in and even see the actual cookies in DevTools Network tab, but the cookie doesn't show up in DevTools Application tab, in Cookie menu.

When I log in to Fauxton, I can see the cookie set by Fauxton, but when I log in with pouchdb-authentication, the cookie list is empty.

So how do I retrieve cookie value then?

**Comment by ptitjes** [comment]
Hi @uyouthe, thanks for your report.

I have no idea why your browser's DevTools does not show the cookie value. If you can indeed succesfully make a call to `getSession()` and retrieve the logged in user informations, then I feel like it is a problem with your browser and not PouchDB Authentication.

Also, could you explain why would you need to retrieve the exact cookie value ?

**Comment by wormling** [comment]
Same problem here.  Just want to manually remove (only) that cookie from time to time during development.

**Comment by whitetigle** [comment]
Same here on both chrome and firefox.

**Comment by ptitjes** [comment]
@uyouthe, @wormling, @whitetigle I figured it out. This is because your database is not hosted on the same sub-domain as your web application, whereas Fauxton is.

So this must be a problem of the browser's DevTools that do not show all the cookies set by the application but just those that are for the same sub-domain.

However, in Firefox, you can go in the 'Privacy & Security' tab of the preferences (aka. `about:preferences#privacy`) and click on the 'remove individual cookies' link in the history section. You then type for the database host domain and should find your `AuthSession` cookie there.

I will therefore close this issue.
