### ISSUE TITLE
Sync authentication times out resulting in a not authorized error.

### ISSUE THREAD

**Issue by MrGurns** [pouchdb-community/pouchdb-authentication#231]
## Expected Behavior
Expecting a persistent live sync after logging into a remote database.

### This code:
```
//initFunction
localDB = new PouchDB('localDB-' + localDataStore.dbName + '-' + envTag, {
   size: 10,
   auto_compaction: true
});
remoteDB = new PouchDB('http://' + localDataStore.dbHost + ':' + localDataStore.dbPort + '/' + localDataStore.dbName, {
   skipSetup: true,
   ajax: {
      cache: false,
      timeout: 30000
   }
});

this.remoteDB.login(localDataStore.dbUser, localDataStore.dbPassword,
{
    ajax: {
        cache: false,
        timeout: 30000
    }
}).then(() => {
    PouchDB.replicate(remoteDB, localDB, {
        include_docs: true,
        return_docs: false,
        conflicts: true,
    })
    .on('change', this.handleChange.bind(this))
    .on('complete', (info) => {
        if (skipUpdateBatch) {
            this.reactToChanges();
            this.syncChanges();
            resolve(true);
        } else {
            this.batchUpdate()
            .then((result) => {
                if (result) {
                    this.reactToChanges();
                    this.syncChanges();
                    resolve(true);
                }
            }).catch((err) => {
                reject(err); //could not update
            });
        }
    })
    .on('denied', (err) => {
        reject(err);
    })
    .on('error', (err) => {
        //unable to sync remote
        reject(err);
    });

}).catch((err) => {
    reject(err);
});

//syncChanges() function
remoteDB.login(dbUser, dbPassword,
{
   ajax: {
      cache: false,
      timeout: 30000
   }
}).then(() => {
   sync = localDB.sync(remoteDB, {
   live: true,
   retry: true,
})
.on('denied', (err) => {
   console.log('[Database::syncChanges()]: Error (1):' + JSON.stringify(err));
})
.on('error', (err) => {
   console.log('[Database::syncChanges()]: Error (2):' + JSON.stringify(err));
});

//reactToChanges() function
this.changes = this.localDB.changes({
    since: 'now',
    live: true,
    retry: true,
    include_docs: true,
    return_docs: false,
    conflicts: true,
})
.on('change', this.handleChange.bind(this))
.on('denied', (err) => {
    console.log('[Database::reactToChanges()]: Error (1):' + JSON.stringify(err));
})
.on('error', (err) => {
    //unable to sync remote
    console.log('[Database::reactToChanges()]: Error (2):' + JSON.stringify(err));
});
```
### Results:
```
[Database::syncChanges()]: Error (2):{"error":"unauthorized","reason":"You are not authorized to access this db.","status":401,"name":"unauthorized","message":"You are not authorized to access this db.","result":{"ok":false,"start_time":"2018-04-05T23:15:40.893Z","docs_read":0,"docs_written":0,"doc_write_failures":0,"errors":[],"last_seq":336,"status":"aborting","end_time":"2018-04-05T23:30:55.297Z"}}
```

## Steps to Reproduce (for bugs)
1. Login to remote db, 
2. Sync local to/from remote, 
3. After 5 minutes or so, make a change that will sync and the error above occurs

## Context
Trying to set up a stable remote sync.

## Your Environment
* Version of PouchDB Authentication: v1.1.2
* Version of PouchDB: v6.4.0
* Platform name and version:  Node.js v6.9.4/React Native v0.52
* Operating System and version:  iOS/Android
* Server: CouchDB
* Link to your project: https://exp.host/@mrgurns/famtastic?release-channel=staging

**Comment by MrGurns** [comment]
I have not seen this issue since adding 
```
headers: {
   Authorization: 'Basic ' + window.btoa(localDataStore.dbUser + ':' + localDataStore.dbPassword)
}
```
Will update if i see it again, as for now i'm closing this.

**Comment by ptitjes** [comment]
Hi @MrGurns. Thanks for the detailed report.


> 3. After 5 minutes or so, make a change that will sync and the error above occurs

This observation makes me wonder whether your problem is only about the authentication cookie becoming stale.

Does the sync work at first ? Could you make a change in the remote database as soon as the client application starts its sync, in order to check that ? If that is indeed the case, then you might try these two options: 1) either configure your remote database for persistent cookies, or 2) periodically call for `getSession()` to reactivate your cookie (say every half of the duration configured on your remote database for authentication cookies).

---

As for your addition of `Authorization` in your last comment, do you have Basic Authentication enabled on your remote database ? If it is not enabled, then the `headers` configuration is not necessary. If it is enabled, then you'd rather use:
```
remoteDB = new PouchDB('http://' + localDataStore.dbHost + ':' + localDataStore.dbPort + '/' + localDataStore.dbName, {
   skipSetup: true,
   auth: {
      username: localDataStore.dbUser,
      password: localDataStore.dbPassword,
   },
   // ...
});
```
With that, PouchDB and PouchDB Authentication will add the `Authorization` by themselves.

However **the best is still to disable the Basic Authentication on your remote database and setup SSL**. That should do it along with the cookie authentication of PouchDB Authentication.

---

Side note: This is totally unrelated to your problem but I believe that your `.on(...)` handlers in `syncChanges()` are misplaced and that they should be inside the preceding `then` block. I just don't understand how you code can work :)

**Comment by MrGurns** [comment]
With the side note, you are correct, that was a copy paste issue on my part.
Thank you much for the detailed answer.

**Comment by mjafarpour** [comment]
Use localStorage for save password has security hole, we use cookies and tokens because save passwords for later use is not safe. @MrGurns 
What is the goal of use cookies??? @ptitjes
